"""Safe local configuration template. Copy to config.py and fill private values locally."""

BOT_NAME = "ADEL SMART BOT ELITE"
VERSION = "local"
MARKET_INDEXES = ["SPX", "SPY", "QQQ", "NASDAQ"]
USE_FEAR_GREED = False
USE_VIX = True
GOLD_SYMBOLS = ["XAUUSD", "GLD"]
BITCOIN_SYMBOLS = ["BTC-USD"]
MARKET_WEIGHT = STRUCTURE_WEIGHT = SMART_MONEY_WEIGHT = MOMENTUM_WEIGHT = PATTERN_WEIGHT = 0
GRADE_A_PLUS = GRADE_A = GRADE_B_PLUS = MIN_SIGNAL_SCORE = 0
TP1_PERCENT = TP2_PERCENT = TP3_PERCENT = STOP_LOSS_PERCENT = 0.0
SCAN_INTERVAL_SECONDS = 60
MIN_OPTION_PRICE = MAX_OPTION_PRICE = 0.0
CONFIDENCE_A_PLUS = CONFIDENCE_A = CONFIDENCE_B = 0
ENABLE_DAILY_REPORT = True
ENABLE_WEEKLY_REPORT = ENABLE_MONTHLY_REPORT = False
HOT_SIGNAL_SCORE = ELITE_SIGNAL_SCORE = 0
WATCHLIST = {"INDICES": [], "ETFS": [], "STOCKS": [], "ENERGY": [], "GOLD": ["GLD"], "BITCOIN": ["BTC-USD"]}

BOT_TOKEN = "REPLACE_WITH_TELEGRAM_BOT_TOKEN"
CHAT_ID = "REPLACE_WITH_TELEGRAM_DESTINATION"
BOT_URL = ""
CHANNEL_URL = "https://t.me/ADELSmartSignals"
ADMIN_ID = "REPLACE_WITH_ADMIN_TELEGRAM_ID"
MOON_SHOT_PERCENT = LEGENDARY_TRADE_PERCENT = MAX_RISK_PER_TRADE = 0.0
PRIMARY_DATA_SOURCE = "MASSIVE"
SECONDARY_DATA_SOURCE = "FINNHUB"
THIRD_DATA_SOURCE = "FMP"
FOURTH_DATA_SOURCE = "ALPHA_VANTAGE"
MIN_HISTORY_ROWS = 200
MASSIVE_API_KEY = "REPLACE_WITH_MASSIVE_KEY"
FINNHUB_API_KEY = "REPLACE_WITH_FINNHUB_KEY"
FMP_API_KEY = "REPLACE_WITH_FMP_KEY"
ALPHA_VANTAGE_API_KEY = "REPLACE_WITH_ALPHA_VANTAGE_KEY"
GEMINI_API_KEY = "REPLACE_WITH_GEMINI_KEY"
USE_MASSIVE = USE_FINNHUB = USE_FMP = USE_ALPHA_VANTAGE = True
ENABLE_SOURCE_FALLBACK = True
USE_REALTIME_DATA = USE_OPTIONS_DATA = USE_FUNDAMENTALS = False
USE_NEWS_DATA = True
USE_MASSIVE_OPTIONS = USE_FMP_FUNDAMENTALS = False
USE_FINNHUB_NEWS = USE_ALPHA_VANTAGE_BACKUP = True
NO_REALTIME_DATA_NO_TRADE = True
ENABLE_TRADIER = ENABLE_ALPACA = ENABLE_IBKR = False
